name: Test Annotate Coverage Action

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Annotate Coverage Action
        uses: drew2a/annotate-coverage-action@v1
        with:
          json_path: "tests/test_coverage.json"
